swagger: "2.0"
info:
  version: "0.0.2"
  title: PotLuck API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /:
    get:
      description: "This endpoint returns all shops available in database"
      operationId: "GetAllShops"
      parameters: []
      responses:
        200:
          description: "an array of shops"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Shop"
      x-swagger-router-controller:
        "GetAllShops"
    post:
      description: "add new shop"
      operationId: "AddShop"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "shop"
        description:  "the shop being added"
        required: true
        schema:
          $ref: "#/definitions/Shop"
      responses:
        200:
          description: "successful shop added"
      x-swagger-router-controller:
          "addShop"
  /shop/{id}:
    get:
      description: "retrieve single shop"
      operationId: "findShopById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of shop"
        required: true
        type: "integer"
      responses:
        200:
          description: "shop response"
          schema:
            $ref: "#/definitions/Shop"
      x-swagger-router-controller:
          "FindTodoByID"
    delete:
      description: "delete single shop"
      operationId: "DeleteTodoById"
      parameters:
      - name: "id"
        in: "path"
        description: "id of the todo to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        204:
          description: "shop deleted"
      x-swagger-router-controller:
        "shop delete by id"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Shop:
    type: "object"
    properties:
      shop_id:
        type: "integer"
        description: "Id for shop"
      location:
        type: "string"
        description: "location of shop"
      name:
        type: "string"
        description: "name of shop"
      description:
        type: "string"
        description: "Description of shop"